# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
#    labels:
#      - dependencies
#      - actions
#      - "Skip Changelog"
    schedule:
      interval: "daily"
#      interval: "weekly"
#      day: "sunday"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/2d"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/cache"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/controls"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/core"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/devoxx-api-cfp"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/devoxx-cfp-test"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/google-cloud"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/logging"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/stepengine-api"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/tweet-impl-twitter4j"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/util"
    schedule:
      interval: "daily"
