////

    The MIT License (MIT)

    Copyright (c) 2017-2019 TweetWallFX

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in
    all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
    THE SOFTWARE.

////

= JavaFX based TweetWall
:toc: macro
:toclevels: 4
:project-full-path: TweetWallFX/TweetwallFX
:github-branch: master
:source-link-base: https://github.com/TweetWallFX/TweetwallFX/blob/{github-branch}

image:https://img.shields.io/badge/license-MIT-blue.svg["MIT License", link="https://github.com/{project-full-path}/blob/{github-branch}/LICENSE"]
image:https://img.shields.io/travis/{project-full-path}/{github-branch}.svg["Build Status", link="https://travis-ci.org/{project-full-path}"]
image:https://api.bintray.com/packages/tweetwallfx-team/maven/org.tweetwallfx/images/download.svg[link="https://bintray.com/tweetwallfx-team/maven/org.tweetwallfx/_latestVersion"]

toc::[]

== Ways to configure Tweetwall

There are several ways to influence and configure a Tweetwall.
Some of these require to be built into the artefact, like <<fxml-and-css,FXML and CSS>>, while others can be set at runtime, like <<system-properties,System Properties>>, and others via <<configuration-file,Configuration Files>> being read at runtime.

=== Configuration Files

Most of the configuration of the Tweetwall is done using configuration files.
The File format JSON and the file content is assumed to be a valid JSON Object.
This enabled the compartmentalized configuration in various places and combination of the compartmentalized parts into a combined form which then represents the actual configuration being used by the application.

==== Location of Configuration Files

The standard name of the configuration files is `tweetwallConfig.json`.
A custom configuration file name can be specified using the <<orgtweetwallconfigfileName,System Property org.tweetwall.config.fileName>>. 

The Configuration files are searched and read from

. any resource found on the Classpath via the resource path `/<FILE_NAME>`,
. from the configuration file in the users home directory via its path `~/<FILE_NAME>`,
. from the configuration file `etc/<FILE_NAME>` of the execution directory of the process and
. from the configuration file `<FILE_NAME>` of the execution directory of the process.

`<FILE_NAME>` in this context is first the standard configuration file name `tweetwallConfig.json`.
In case the <<orgtweetwallconfigfileName,System Property org.tweetwall.config.fileName>> is set and its value is a different value than the standard configuration file name then those files will be read afterwards.

==== Combining compartmentalized Configuration

The Configuration files - those with the standard configuration file name and those identified from the <<orgtweetwallconfigfileName,System Property org.tweetwall.config.fileName>> - are each read in order and merged into one combined virtual file.

The algorithm for the combination starts out with an empty JSON Object and - one by one - merges each configuration fragment onto that JSON - handled by <<merging-json-objects>>.

===== Merging JSON Objects

Code: link:{source-link-base}/config/src/main/java/org/tweetwallfx/config/Configuration.java#L307-L318[Configuration::mergeMap]

Two JSON Objects are merged by merging the attributes of the new JSON Object onto those of the existing JSON Object - handled by <<merging-json-attribute-value,Merging JSON Attribute Value>>.

===== Merging JSON Attribute Value

Code: link:{source-link-base}/config/src/main/java/org/tweetwallfx/config/Configuration.java#L320-L348[Configuration::mergeValue]

The result of a merge of two Attribute Values - in general terms - is either

. an actual merge of the values structure in case of a complex type or
. the replacement of the old value with the new value.

A JSON Object or an JSON Array is considered to be a complex structure in this context.

Merging two JSON Arrays will result in the new value to replace the previous value as reordering or filtering of an arrays content is not supported.

Merging two JSON Objects will be handled by <<merging-json-objects,Merging JSON Objects>>.

=== FXML and CSS

TODO: Add content

=== System Properties

Certain values are configurable via System Properties.
They can be set e.g. by adding a link:++https://docs.gradle.org/current/dsl/org.gradle.api.tasks.JavaExec.html#org.gradle.api.tasks.JavaExec:jvmArgs(java.lang.Object[])++[jvmArg] on a https://docs.gradle.org/current/dsl/org.gradle.api.tasks.JavaExec.html[JavaExec] task in gradle or any similiar way.
Setting these values is usually used during development or to test a configuration as these property values will be used instead of a value derived at runtime.
This can be the case when testing a schedule display for a day and time in the future.

==== org.tweetwallfx.scheduledata.day

This property sets the value of the day used for displaying schedule based data instead of the determined day name.

* link:{source-link-base}/devoxx-cfp-stepengine/src/main/java/org/tweetwallfx/devoxx/cfp/stepengine/dataprovider/ScheduleDataProvider.java[ScheduleDataProvider] uses the name of the day in order to display the upcoming schedule of the day.
* link:{source-link-base}/devoxx-cfp-stepengine/src/main/java/org/tweetwallfx/devoxx/cfp/stepengine/dataprovider/TopTalksTodayDataProvider.java[TopTalksTodayDataProvider] uses the name of the day to display the top rated talks of the day.

Example values may be:

* `monday`
* `tuesday`
* `wednesday`
* `thursday`
* `friday`
* `saturday`
* `sunday`

==== org.tweetwallfx.scheduledata.time

This property sets the value of the time used for displaying schedule based data instead of the determined time.

* link:{source-link-base}/devoxx-cfp-stepengine/src/main/java/org/tweetwallfx/devoxx/cfp/stepengine/dataprovider/ScheduleDataProvider.java[ScheduleDataProvider] uses the time to filter for the currently active or upcoming schedule slots.

Example values may be:

* `10:00Z`
* `09:53Z`
* `14:15Z`

==== org.tweetwallfx.scheduledata.proposal

This property sets the ID of a Talk to display.

* link:{source-link-base}/devoxx-cfp-stepengine/src/main/java/org/tweetwallfx/devoxx/cfp/stepengine/dataprovider/VotedTalk.java[VotedTalk] uses the ID in order to select the talk being displayed in the voted talks Visualization.

Example values may be:

* `CTH-5247`
* or any other Talk ID from the CFP.

==== org.tweetwall.config.fileName

This property sets a custom file name (including extension) for Configuration files to be read when combining the compartmentalized configuration segments into a combined data structure.

Example values may be:

* `myConfig.json`
* `cinema.json`

== Configuration File Sections

The combined Configuration - in effect a JSON Object - may contain several configuration sections in the form of the JSONs attributes.

=== TODO: cacheConfiguration
TODO: Add content

=== connectionSettings

Settings concerning the HTTP Connections.

sectionName:: `connectionSettings`
class:: `org.tweetwallfx.config.ConnectionSettings` (link:{source-link-base}/config/src/main/java/org/tweetwallfx/config/ConnectionSettings.java[source])
converted to POJO:: After raw Configuration Data has been loaded

.Structure of `tweetwallConfig.json` with this configuration structure only
[source,plain]
----
{
  "connectionSettings": {
    "proxy": {
      "host",
      "port",
      "user"",
      "password";
    }
  }
}
----

[options="header", cols="5*"]
|===
| Name | Type | Required | Default Value | Description

| connectionSettings | `link:{source-link-base}/config/src/main/java/org/tweetwallfx/config/ConnectionSettings.java[org.tweetwallfx.config.ConnectionSettings]` | NO | | Name of Configuration section
| proxy | `link:{source-link-base}/config/src/main/java/org/tweetwallfx/config/ConnectionSettings.java#L82-L174[org.tweetwallfx.config.ConnectionSettings$Proxy]` | NO | `null` | Proxy setting to use when working with HTTP Connections.
| host | `java.lang.String` | NO | `""` | Host address of proxy server to use.
| port | `int` | NO | `-1` | Port number of the proxy server to use.
| user | `java.lang.String` | NO | `""` | User name to use for the proxy connection.
| password | `java.lang.String` | NO | `""` | Password to use for the proxy connection.
|===

=== TODO: devoxxCFP
TODO: Add content

=== TODO: filterchains
TODO: Add content

=== google

Settings for interaction with Google APIs.

sectionName:: `google`
class:: `org.tweetwallfx.google.GoogleSettings` (link:{source-link-base}/google-cloud/src/main/java/org/tweetwallfx/google/GoogleSettings.java[source])
converted to POJO:: After raw Configuration Data has been loaded

.Structure of `tweetwallConfig.json` with this configuration structure only
[source,plain]
----
{
  "google": {
    "credentialFilePath",
    "cloudVision": {
      "featureTypes"
    }
  }
}
----

[options="header", cols="5*"]
|===
| Name | Type | Required | Default Value | Description

| google | `link:{source-link-base}/google-cloud/src/main/java/org/tweetwallfx/google/GoogleSettings.java[org.tweetwallfx.google.vision.GoogleSettings]` | NO | | Name of Configuration section
| credentialFilePath | `java.lang.String` | NO | `null` | Path to the credentials required for the authentication with Google APIs. Credentials file can be gotten from https://console.cloud.google.com.
| cloudVision | `link:{source-link-base}/google-cloud/src/main/java/org/tweetwallfx/google/vision/CloudVisionSettings.java[org.tweetwallfx.google.vision.CloudVisionSettings]` | NO | `null` | Settings concerning the Google Cloud Vision APIs.
| featureTypes | `java.util.Set<link:{source-link-base}/google-cloud/src/main/java/org/tweetwallfx/google/vision/CloudVisionSettings.java#L52-L65[org.tweetwallfx.google.vision.CloudVisionSettings$FeatureType]>` | NO | `["SAFE_SEARCH_DETECTION", "TEXT_DETECTION"]` | Sets the features that are to requested in a request for image analysis by Google Cloud Vision API.
|===

=== tweetwall

Settings for the Tweetwall Application in general.

sectionName:: `tweetwall`
class:: `org.tweetwallfx.config.TweetwallSettings` (link:{source-link-base}/config/src/main/java/org/tweetwallfx/config/TweetwallSettings.java[source])
converted to POJO:: After raw Configuration Data has been loaded

.Structure of `tweetwallConfig.json` with this configuration structure only
[source,plain]
----
{
  "tweetwall": {
    "title",
    "stylesheetResource",
    "stylesheetFile",
    "query"
  }
}
----

[options="header", cols="5*"]
|===
| Name | Type | Required | Default Value | Description

| tweetwall | `link:{source-link-base}/config/src/main/java/org/tweetwallfx/config/TweetwallSettings.java[org.tweetwallfx.config.TweetwallSettings]` | YES | | Name of Configuration section
| title | `java.lang.String` | YES | `null` | title of the Tweetwall. Title will be set on the stage.
| stylesheetResource | `java.lang.String` | NO | `null` | Resource path containing stylesheet to be read from the Classpath. When set will be added to list of stylesheets known to the scene of Tweetwall.
| stylesheetFile | `java.lang.String` | NO | `null` | Resource path containing stylesheet to be read from the filesystem. When set will be added to list of stylesheets known to the scene of Tweetwall.
| query | `java.lang.String` | YES | `null` | Query String that is used to provide Tweets for the Tweetwall. Any that that contains any of the words provided in this String will be processed by the Tweetwall. The words can be regular words, hashtags or user handles.
|===

=== twitter

Settings concerning the twitter client.

sectionName:: `twitter`
class:: `org.tweetwallfx.tweet.api.config.TwitterSettings` (link:{source-link-base}/tweet-api/src/main/java/org/tweetwallfx/tweet/api/config/TwitterSettings.java[source])
converted to POJO:: After raw Configuration Data has been loaded

.Structure of `tweetwallConfig.json` with this configuration structure only
[source,plain]
----
{
  "twitter": {
    "debugEnabled",
    "extendedConfig",
    "extendedMode",
    "ignoreRateLimit",
    "oauth: {
      "consumerKey",
      "consumerSecret",
      "accessToken",
      "accessTokenSecret"
    }
  }
}
----

[options="header", cols="5*"]
|===
| Name | Type | Required | Default Value | Description

| twitter | `link:{source-link-base}/tweet-api/src/main/java/org/tweetwallfx/tweet/api/config/TwitterSettings.java[org.tweetwallfx.tweet.api.config.TwitterSettings]` | YES | | Name of Configuration section
| debugEnabled | `boolean` | NO | `false` | Flag indicating that the twitter client is to work in debug mode.
| extendedConfig | `java.lang.String` | NO | `[:]` | Extended configuration for the Twitter Client.
| extendedMode | `boolean` | NO | `false` | Flag indicating that the Twitter Client is to work in extended mode
| ignoreRateLimit | `boolean` | NO | `true` | Flag indicating that the Twitter API rate limitations shall be ignored by the Twitter Client.
| oauth | `link:{source-link-base}/tweet-api/src/main/java/org/tweetwallfx/tweet/api/config/TwitterSettings.java#L180-L272[org.tweetwallfx.tweet.api.config.TwitterSettings$Oauth]` | YES | | OAuth settings the Twitter client is to use in order to connect with Twitter APIs.
| consumerKey | `java.lang.String` | YES | | The Consumer Key of the Twitter Credentials to use for the Twitter Client.
| consumerSecret | `java.lang.String` | YES | | The Consumer Secret of the Twitter Credentials to use for the Twitter Client.
| accessToken | `java.lang.String` | YES | | The Access Token of the Twitter Credentials to use for the Twitter Client.
| accessTokenSecret | `java.lang.String` | YES | | The Access Token Secret of the Twitter Credentials to use for the Twitter Client.
|===

The values of the four oauth attribute value (`consumerKey`, `consumerSecret`, `accessToken` and `accessTokenSecret`) are values of Twitter Credentials. The Credentials can be retrieved from https://developer.twitter.com/.

=== TODO: org.tweetwallfx.google.vision.ImageContentFilterStep$Config
TODO: Add content

=== TODO: org.tweetwallfx.tweet.api.filter.AcceptFromSenderFilterStep$Config
TODO: Add content

=== TODO: org.tweetwallfx.tweet.api.filter.MaxHashtagLengthFilterStep$Config
TODO: Add content

=== TODO: org.tweetwallfx.tweet.api.filter.RejectFromSenderFilterStep$Config
TODO: Add content

=== TODO: org.tweetwallfx.tweet.api.filter.UserMinimumFollwerCountFilterStep$Config
TODO: Add content

== Example Configuration File

.tweetwallConfig.json
[source,json]
----
{

    "customize_filterchains": {
        "chains": {
            "twitter": {
                "domainObjectClassName": "org.tweetwallfx.tweet.api.Tweet",
                "defaultResult": true,
                "filterSteps": [
                    {
                        "stepClassName": "org.tweetwallfx.tweet.api.filter.AcceptFromSenderFilterStep"
                    },
                    {
                        "stepClassName": "org.tweetwallfx.tweet.api.filter.RejectFromSenderFilterStep"
                    },
                    {
                        "stepClassName": "org.tweetwallfx.tweet.api.filter.UserMinimumFollwerCountFilterStep"
                    },
                    {
                        "stepClassName": "org.tweetwallfx.tweet.api.filter.MaxHashtagLengthFilterStep"
                    },
                    {
                        "stepClassName": "org.tweetwallfx.google.vision.ImageContentFilterStep"
                    }
                ]
            }
        }
    },
    "comment for customize_filterchain": [
        "The origianl block name is filterchain. If you rename the previous block",
        "to that name you can customize the filterchains.",
        "",
        "The 'twitter' chain is used to evaluate if a Tweet received from Twitter",
        "(using the query from the 'tweetwall' block) is to be processed by the",
        "Tweetwall. An object - in this case an object of the declared",
        "'domainObjectClassName' is passed in order through the filter step. As",
        "soon as any one of those finds a definite reason to accept/reject the",
        "object it is handled accordingly. If no definite reason was found then",
        "the object is accepted if 'defaultResult' is true.",
        "",
        "The steps themselves are also configurable and will follow hereafter in",
        "their default configuration as they are commited in the github repository.",
        "",
        "In case you don't/have Google Cloud Vision filtering you can remove the step",
        "using that feature (i.e. 'org.tweetwallfx.google.vision.ImageContentFilterStep'."
    ],

    "org.tweetwallfx.tweet.api.filter.AcceptFromSenderFilterStep$Config": {
        "checkRetweeted": false,
        "userHandles": [
            "Devoxx"
        ]
    },
    "comment for org.tweetwallfx.tweet.api.filter.AcceptFromSenderFilterStep$Config": [
        "This block configures the aforementioned filter step in that it declares",
        "the user handler of twitter user that will have all their tweets processed",
        "by the Tweetwall display."
    ],

    "org.tweetwallfx.tweet.api.filter.MaxHashtagLengthFilterStep$Config": {
        "checkRetweeted": true,
        "maxLength": 15
    },
    "comment for org.tweetwallfx.tweet.api.filter.MaxHashtagLengthFilterStep$Config": [
        "This block configures the aforementioned filter step in that it declares",
        "the maximum length of any hashtag in a tweet that might still be acceptable",
        "by other filter steps. If a hashtag has a length larger than declared here",
        "then the tweet will be rejected from being processed by the Tweetwall",
        "display.",
        "This is a low level attempt at rejecting bots and others from junping on",
        "a trending hashtag."
    ],

    "org.tweetwallfx.tweet.api.filter.RejectFromSenderFilterStep$Config": {
        "checkRetweeted": true,
        "userHandles": [
            "turkeytoday"
        ]
    },
    "comment for org.tweetwallfx.tweet.api.filter.RejectFromSenderFilterStep$Config": [
        "This block configures the aforementioned filter step in that it declares",
        "the user handler of twitter user that will have noone of their tweets",
        "processed by the Tweetwall display.",
        "@turkeytoday crossposted with the devoxx hashtag last year during Devoxx BE."
    ],

    "org.tweetwallfx.tweet.api.filter.UserMinimumFollwerCountFilterStep$Config": {
        "count": 25
    },
    "comment for org.tweetwallfx.tweet.api.filter.UserMinimumFollwerCountFilterStep$Config": [
        "This block configures the aforementioned filter step in that it declares",
        "the minimum number of followers a twitter user has to have to not have his/her tweets rejected.",
        "This is a low level attempt at rejecting bots and others from junping on",
        "a trending hashtag as was the case 2017 with the russian spam bots."
    ],

    "org.tweetwallfx.google.vision.ImageContentFilterStep$Config": {
        "checkRetweeted": true,
        "adult": {
            "acceptableLikelyhood": "VERY_UNLIKELY"
        },
        "medical": {
            "acceptableLikelyhood": "UNLIKELY"
        },
        "racy": {
            "acceptableLikelyhood": "VERY_UNLIKELY"
        },
        "spoof": {
            "acceptableLikelyhood": "UNLIKELY"
        },
        "violence": {
            "acceptableLikelyhood": "VERY_UNLIKELY"
        }
    },
    "comment for org.tweetwallfx.google.vision.ImageContentFilterStep$Config": [
        "This block configures the aforementioned filter step in that it declares",
        "the acceptableLikelyhood (see Google Cloud Vision API) that has to be",
        "reached for images in a tweet in order to be processed by the Tweetwall",
        "display. If the tweet does not have an image the tweet is passed to the",
        "next filter step.",
        "This step took about 1200ms a call last year during devoxx be."
    ]
}
----

== Getting OAuth keys

Create a new Application for TweetWall within https://apps.twitter.com[Twitter Apps site] signing in with the twitter account that will be used to run the TweetWallFX.
You have to enter at least the website of your company. After doing so generate a new access token under `Keys and Access Tokens`.

Update your Configuration file `tweetwallConfig.json` and configure the <<twitter,Configuration Section twitter>>.

