# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle Build

on:
  push:
    branches:
      - master
      - release
  pull_request:
    branches:
      - master
      - release

jobs:
  build:
    name: Build with JDK ${{ matrix.jdk }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        jdk:
          - '11'
#          - '17' #disabled for now

    steps:
      # Check out sources
      - name: Fetch Sources
        uses: actions/checkout@v3

      # Validate wrapper
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4

      # Setup JDK environment for the next steps
      - name: Setup JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdk }}
          cache: gradle

      # Run assemble tasks
      - name: Run assemble tasks
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: --no-daemon --refresh-dependencies --info assemble

      # Run test tasks
      - name: Run test tasks
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: --no-daemon --info test

      # Run check tasks
      - name: Run check tasks
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: --no-daemon --info check
